### ISSUE TITLE
Handle error in undefined property definitions 

### ISSUE THREAD

**Issue by sk593** [radius-project/bicep-types-aws#93]
There's an issue in the publish-bicep.yaml workflow where properties are being referenced with no actual definition. For example, this is a referenced property but has no definition: 
```
          "Interactions": {
            "$ref": "#/definitions/VisualInteractionOptions"
          },
```

```
An error was encountered while handling a request: Error: could not find definition #/definitions/VisualInteractionOptions in Analysis_Interactions
    at visitSchema (/home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:212:23)
    at /home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:267:34
    at Array.forEach (<anonymous>)
    at createType (/home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:266:51)
    at visitSchema (/home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:303:16)
    at /home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:167:9
    at Array.forEach (<anonymous>)
    at visitDefinitions (/home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:166:[47](https://github.com/radius-project/bicep-types-aws/actions/runs/12009498164/job/33474343787?pr=92#step:10:48))
    at visitSchemaRecord (/home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:20:5)
    at /home/runner/work/bicep-types-aws/bicep-types-aws/src/aws-type-generator/dist/src/convert.js:10:9
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
```

We should see if there's an error in the download code or if this is a discrepancy with the AWS documentation 

[AB#13749](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13749)

**Comment by sk593** [comment]
Addressed by #96
